<?php

namespace Worm\SiteBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * SubmissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubmissionRepository extends EntityRepository
{

    /**
     * @param $alias
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getBaseQueryBuilder($alias)
    {
        return $this
            ->createQueryBuilder($alias)
            ->leftJoin(sprintf('%s.author', $alias), sprintf('%s_u', $alias))
            ->addOrderBy(sprintf('%s.submittedAt', $alias), 'ASC');
    }

    /**
     * @return array|null
     */
    public function retrieveAll()
    {
        try {
            return $this
                ->getBaseQueryBuilder('s')
                ->getQuery()
                ->getResult();
        } catch (NoResultException $e) {
            return null;
        }
    }
}
