<?php

namespace Worm\SiteBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionRepository extends EntityRepository
{

    /**
     * @param $id
     * @param $position
     * @return mixed
     */
    public function findOne($id, $position)
    {
        $q = $this
            ->createQueryBuilder('s')
            ->join('s.worm', 'w')
            ->andWhere('w.id = :worm_id')
            ->andWhere('s.position = :position');

        $q->setParameters(
            array(
                'worm_id' => $id,
                'position' => $position
            )
        );

        return $q->getQuery()->getOneOrNullResult();
    }
}
