<?php

namespace Worm\SiteBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * WormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WormRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function retrieveAllWorms()
    {
        $queryBuilder = $this->createQueryBuilder('w');

        $queryBuilder->orderBy('w.createdAt', 'DESC');

        try {
            return $queryBuilder
                ->getQuery()
                ->getResult();
        } catch (NoResultException $e) {
            return array();
        }
    }
}
