<?php

namespace Worm\SiteBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WormRepository extends EntityRepository
{
}
