<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121226191952 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE ws_submission (id INT AUTO_INCREMENT NOT NULL, author_user_id INT DEFAULT NULL, hash VARCHAR(40) NOT NULL, extension VARCHAR(4) NOT NULL, size INT NOT NULL, UNIQUE INDEX UNIQ_48EE743DD1B862B8 (hash), INDEX IDX_48EE743DE2544CD6 (author_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE ws_submission ADD CONSTRAINT FK_48EE743DE2544CD6 FOREIGN KEY (author_user_id) REFERENCES ws_user (id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE ws_user ADD position INT NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE ws_submission");
        $this->addSql("ALTER TABLE ws_user DROP position");
    }
}
