parameters:

services:
    worm_site.queue:
        class: Worm\SiteBundle\Queue\QueueManager
        arguments:
            - %worm_site.queue.root_path%
            - @doctrine.orm.entity_manager
            - @event_dispatcher