parameters:
    worm_site.image.root_path: %kernel.root_dir%/../web/upload/
    worm_site.image.web_path: /upload/

services:
    worm_site.image_manager:
        class: Worm\SiteBundle\Image\ImageManager
        arguments:
            - @validator
            - %worm_site.image.root_path%
            - %worm_site.image.web_path%

    security.access.worm_voter:
        class: Worm\SiteBundle\Security\Voter\WormVoter
        arguments: [@security.role_hierarchy]
        public: false
        tags:
            - {name: security.voter}

    security.access.subscription_voter:
        class: Worm\SiteBundle\Security\Voter\SubscriptionVoter
        arguments: [@security.role_hierarchy]
        public: false
        tags:
            - {name: security.voter}